name: whispair_loopmind
description: >-
  Whispair LoopMind MVP mobile application connecting the Whispair pendant with
  AI transcription and ideation workflows.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  flutter_blue_plus: ^1.31.16
  just_audio: ^0.9.36
  opus_dart: ^3.1.2
  path_provider: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  collection: ^1.18.0
  intl: ^0.19.0
  http: ^1.2.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  supabase_flutter: ^2.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2

dependency_overrides:
  meta: ^1.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
